# Generated by Django 2.0 on 2019-04-24 04:38

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190424_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 4, 24, 4, 38, 24, 601698)),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='NGN', max_digits=50),
        ),
    ]
