# Generated by Django 2.0 on 2019-04-25 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190424_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 4, 25, 2, 53, 25, 609196)),
        ),
    ]
