# Generated by Django 2.0 on 2019-04-25 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20190425_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 4, 25, 5, 5, 32, 891419)),
        ),
    ]
