# Generated by Django 2.0 on 2019-05-06 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20190505_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 5, 6, 13, 31, 40, 37749)),
        ),
    ]
