# Generated by Django 2.0 on 2019-05-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20190508_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rate_2',
            field=models.CharField(default='5', max_length=22),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
