# Generated by Django 2.0 on 2019-05-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20190508_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='resto_type',
            field=models.CharField(choices=[('Amsterdamseweg 114 Next to Molen, 1182 HH, Amstelveen The Netherlands', 'Amsterdamseweg 114 Next to Molen, 1182 HH, Amstelveen The Netherlands'), ('Piet Mondriaanplein 189-193, 3812 GZ Amersfoort, The Netherlands', 'Piet Mondriaanplein 189-193, 3812 GZ Amersfoort, The Netherlands')], default='Amsterdamseweg 114 Next to Molen, 1182 HH, Amstelveen The Netherlands', max_length=400),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rate_2',
            field=models.CharField(max_length=22),
        ),
    ]
