# Generated by Django 2.0 on 2019-06-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20190625_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='Menu_type',
            field=models.CharField(choices=[('Takeaway', 'Takeaway'), ('Home Delivery', 'Home Delivery')], default='Home Delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Soepen', 'Soepen'), ('Voorgerechten', 'Voorgerechten'), ('Momo gerechten', 'Momo gerechten'), ('Noodle gerechten', 'Noodle gerechten'), ('Tandoori gerechten', 'Tandoori gerechten'), ('Kipgerechten', 'Kipgerechten'), ('Lamsgerechten', 'Lamsgerechten'), ('Zeevruchten gerechten', 'Zeevruchten gerechten'), ('Vegetarische gerechten', 'Vegetarische gerechten'), ('Biryani gerechten', 'Biryani gerechten'), ("Extra's", "Extra's"), ('Indiaas brood', 'Indiaas brood'), ('Nagerechten', 'Nagerechten'), ('Dranken', 'Dranken')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
