# Generated by Django 2.0 on 2019-07-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='dutch_description',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
    ]
