# Generated by Django 2.0 on 2019-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_menuitem_dutch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Soepen', 'Soepen'), ('Voorgerechten', 'Voorgerechten'), ('Momo gerechten', 'Momo gerechten'), ('Nepali Menu', 'Nepali Menu'), ('Noodle gerechten', 'Noodle gerechten'), ('Tandoori gerechten', 'Tandoori gerechten'), ('Kipgerechten', 'Kipgerechten'), ('Lamsgerechten', 'Lamsgerechten'), ('Zeevruchten gerechten', 'Zeevruchten gerechten'), ('Vegetarische gerechten', 'Vegetarische gerechten'), ('Biryani gerechten', 'Biryani gerechten'), ("Extra's", "Extra's"), ('Indiaas brood', 'Indiaas brood'), ('Nagerechten', 'Nagerechten'), ('Dranken', 'Dranken')], default='available', max_length=30),
        ),
    ]
